[package]
name = "roget"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# disable build script
build = false

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true

[dependencies]
# clap = { version = "3", features = ["derive"] }
once_cell = "1"
wasm-bindgen = "0.2.83"
